import {
  TbBrandAdobePhotoshop,
  TbBrandMysql,
  TbBrandRedux,
  TbSql,
  TbBrandTypescript,
  TbBrandVercel,
  TbBrandVite,
  TbBrandTeams,
  TbSparkles,
} from "react-icons/tb";
import {
  BiLogoGraphql,
  BiLogoJquery,
  BiLogoHtml5,
  BiLogoCss3,
  BiLogoMarkdown,
  BiTransfer,
} from "react-icons/bi";
import {
  FaBootstrap,
  FaChrome,
  FaCode,
  FaDatabase,
  FaDocker,
  FaFigma,
  FaGit,
  FaGithub,
  FaNodeJs,
  FaReact,
  FaServer,
  FaSlack,
  FaTools,
  FaWindows,
} from "react-icons/fa";
import {
  SiAxios,
  SiExpress,
  SiHandlebarsdotjs,
  SiHeroku,
  SiInsomnia,
  SiJest,
  SiJsonwebtokens,
  SiMantine,
  SiMocha,
  SiMongodb,
  SiMongoose,
  SiNextdotjs,
  SiPostman,
  SiSass,
  SiSequelize,
  SiSocketdotio,
  SiSwagger,
  SiNpm,
  SiNvm,
  SiCanva,
  SiExcalidraw,
  SiJira,
  SiConfluence,
  SiZoom,
  SiDiscord,
  SiMacos,
} from "react-icons/si";
import { RiJavascriptLine } from "react-icons/ri";
import { DiResponsive } from "react-icons/di";
import { IoAccessibilitySharp } from "react-icons/io5";
import { VscVscode } from "react-icons/vsc";
import { LuFile } from "react-icons/lu";
import { GrOracle } from "react-icons/gr";
import type { IconType } from "react-icons";

type SkillItem = {
  label: string;
  icon: IconType;
};

type SkillSection = {
  title: string;
  icon: IconType;
  items: Array<SkillItem | { label: string; kind: "subheading" }>;
};

export const skills: SkillSection[] = [
  {
    title: "Languages",
    icon: FaCode,
    items: [
      { label: "JavaScript", icon: RiJavascriptLine },
      { label: "TypeScript", icon: TbBrandTypescript },
      { label: "jQuery", icon: BiLogoJquery },
      { label: "SQL", icon: TbSql },
      { label: "HTML5", icon: BiLogoHtml5 },
      { label: "CSS3", icon: BiLogoCss3 },
      { label: "Markdown", icon: BiLogoMarkdown },
    ],
  },
  {
    title: "Frontend",
    icon: FaReact,
    items: [
      { label: "Frameworks", kind: "subheading" },
      { label: "React", icon: FaReact },
      { label: "Next.js", icon: SiNextdotjs },
      { label: "Vite", icon: TbBrandVite },
      { label: "Handlebars.js", icon: SiHandlebarsdotjs },
      { label: "Styling", kind: "subheading" },
      { label: "CSS3", icon: BiLogoCss3 },
      { label: "Sass", icon: SiSass },
      { label: "Bootstrap", icon: FaBootstrap },
      { label: "Telerik Kendo UI", icon: LuFile },
      { label: "ReactStrap", icon: LuFile },
      { label: "Mantine UI", icon: SiMantine },
      { label: "Testing & Tools", kind: "subheading" },
      { label: "Jest", icon: SiJest },
      { label: "React Testing Library", icon: FaReact },
      { label: "Redux", icon: TbBrandRedux },
      { label: "Axios", icon: SiAxios },
      { label: "Validate.js", icon: LuFile },
      { label: "RESTful APIs", icon: BiTransfer },
      { label: "Responsive Design", icon: DiResponsive },
      { label: "Web Accessibility", icon: IoAccessibilitySharp },
    ],
  },
  {
    title: "Backend",
    icon: FaServer,
    items: [
      { label: "Frameworks", kind: "subheading" },
      { label: "Node.js", icon: FaNodeJs },
      { label: "Express.js", icon: SiExpress },
      { label: "Testing", kind: "subheading" },
      { label: "Mocha", icon: SiMocha },
      { label: "SuperTest", icon: BiTransfer },
      { label: "Authentication & APIs", kind: "subheading" },
      { label: "JWT Authentication", icon: SiJsonwebtokens },
      { label: "RESTful APIs", icon: BiTransfer },
      { label: "GraphQL", icon: BiLogoGraphql },
      { label: "Socket.io", icon: SiSocketdotio },
      { label: "Documentation & Logging", kind: "subheading" },
      { label: "Swagger", icon: SiSwagger },
      { label: "Log4js", icon: LuFile },
      { label: "Axiom", icon: LuFile },
    ],
  },
  {
    title: "Databases",
    icon: FaDatabase,
    items: [
      { label: "SQL Databases", kind: "subheading" },
      { label: "MySQL", icon: TbBrandMysql },
      { label: "Sequelize ORM", icon: SiSequelize },
      { label: "Oracle PL/SQL", icon: GrOracle },
      { label: "NoSQL Databases", kind: "subheading" },
      { label: "MongoDB", icon: SiMongodb },
      { label: "Mongoose", icon: SiMongoose },
    ],
  },
  {
    title: "Tools & Platforms",
    icon: FaTools,
    items: [
      { label: "Development Tools", kind: "subheading" },
      { label: "VS Code", icon: VscVscode },
      { label: "Postman", icon: SiPostman },
      { label: "Insomnia", icon: SiInsomnia },
      { label: "MongoDB Compass", icon: SiMongodb },
      { label: "npm", icon: SiNpm },
      { label: "nvm (Node Version Manager)", icon: SiNvm },
      { label: "Chrome DevTools", icon: FaChrome },
      { label: "Git", icon: FaGit },
      { label: "Microsoft SQL Server Management Studio", icon: LuFile },
      { label: "Oracle SQL Developer", icon: LuFile },
      { label: "Deployment", kind: "subheading" },
      { label: "Docker", icon: FaDocker },
      { label: "Heroku", icon: SiHeroku },
      { label: "Vercel", icon: TbBrandVercel },
      { label: "Design Tools", kind: "subheading" },
      { label: "Figma", icon: FaFigma },
      { label: "Canva", icon: SiCanva },
      { label: "Excalidraw", icon: SiExcalidraw },
      { label: "Adobe Photoshop", icon: TbBrandAdobePhotoshop },
      { label: "Project Management", kind: "subheading" },
      { label: "Jira", icon: SiJira },
      { label: "Confluence", icon: SiConfluence },
      { label: "Communication", kind: "subheading" },
      { label: "Microsoft Teams", icon: TbBrandTeams },
      { label: "Slack", icon: FaSlack },
      { label: "Zoom", icon: SiZoom },
      { label: "Discord", icon: SiDiscord },
      { label: "Platforms", kind: "subheading" },
      { label: "GitHub", icon: FaGithub },
      { label: "Windows", icon: FaWindows },
      { label: "macOS", icon: SiMacos },
    ],
  },
  {
    title: "Best Practices",
    icon: TbSparkles,
    items: [
      { label: "Methodologies", kind: "subheading" },
      { label: "Agile Methodologies (Scrum, Kanban)", icon: LuFile },
      { label: "Test-Driven Development (TDD)", icon: LuFile },
      { label: "Continuous Integration/Continuous Deployment (CI/CD)", icon: LuFile },
      { label: "Pair Programming", icon: LuFile },
      { label: "Code Reviews", icon: LuFile },
      { label: "Version Control", kind: "subheading" },
      { label: "Git", icon: FaGit },
      { label: "Design & Architecture", kind: "subheading" },
      { label: "MVC Architecture", icon: LuFile },
      { label: "Responsive Web Design", icon: DiResponsive },
      { label: "Mobile-First Development", icon: LuFile },
      { label: "Quality & Security", kind: "subheading" },
      { label: "Password Manager (e.g. Keeper)", icon: LuFile },
      { label: "Environment Variables for Sensitive Data", icon: LuFile },
      { label: "Obfuscation of Client-Side Code", icon: LuFile },
    ],
  },
];